//
// Created by PC-SAMUEL on 28/11/2024.
//

#ifndef SOULS_VISION_RESOURCES_H
#define SOULS_VISION_RESOURCES_H

#define IDR_AGMENA_W1G_FONT 101
#define IDR_BAR_PNG 201
#define IDR_BAR_BG_PNG 202
#define IDR_BAR_EDGE_PNG 203
#define IDR_BAR_EDGE_2_PNG 204
#define IDR_BLUE_PNG 205
#define IDR_BUDDY_WAKU_PNG 206
#define IDR_CONDITION_WAKU_PNG 207
#define IDR_DEATHBLIGHT_PNG 208
#define IDR_FIRE_PNG 209
#define IDR_FROSTBITE_PNG 210
#define IDR_GREEN_PNG 211
#define IDR_GREEN_ARROW_PNG 212
#define IDR_HEMORRHAGE_PNG 213
#define IDR_HOLY_PNG 214
#define IDE_LIGHTNING_PNG 215
#define IDR_MADNESS_PNG 216
#define IDR_MAGIC_PNG 217
#define IDR_POISON_PNG 218
#define IDR_RED_PNG 219
#define IDE_RED_ARROW_PNG 220
#define IDR_SCARLET_ROT_PNG 221
#define IDR_SLEEP_PNG 222
#define IDR_YELLOW_PNG 223

#endif //SOULS_VISION_RESOURCES_H
